
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  
  if (request.action === "SUMMARIZE_TEXT") {
    console.log("Background received text to summarize. Length:", request.text.length);

    // Simulate the delay of a network request to an AI API
    setTimeout(() => {
      sendResponse({
        success: true,
        summary: "This is a test summary generated by the Background Worker! \n\n• Point 1: The pipeline is fully connected.\n• Point 2: We are ready to add the real AI API."
      });
    }, 1500);

    // I returned TRUE  to tell Chrome this is an asynchronous response
    return true; 
  }
});